### ISSUE TITLE
having duplicate keys for any object breaks the linter

### ISSUE THREAD

**Issue by salahalsaleh** [replicatedhq/kots-lint#23]
for example
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nginx
  labels:
    app: example
    component: nginx
spec:
  replicas: 1
  replicas: 1
```
